build: install build-gqty build-rsbuild

# Auth webhook server
server-dev:
    cd server && deno run --watch --allow-net --allow-env main.ts

server-start:
    cd server && deno run --allow-net --allow-env main.ts

server-install:
    cd server && deno install

build-rsbuild:
    export PUBLIC_GIT_COMMIT_SHA=$(git rev-parse HEAD)
    deno run -A npm:@rsbuild/core build

build-gqty:
    deno run -A npm:@gqty/cli generate

dev: build-gqty
    deno run -A npm:@rsbuild/core dev --open

install:
    deno install

start:
    deno run -A npm:@rsbuild/core preview

lint:
    deno lint

# End-to-end browser tests via headless Servo + WebDriver
test-browser:
    nu test-browser.nu

# Browser tests with verbose Servo output (debugging)
test-browser-verbose:
    nu test-browser.nu --verbose

# Single page browser test (home, login, register, js, routing)
test-browser-page page:
    nu test-browser.nu --page {{ page }}

# Browser tests using existing dist/ (skip build check)
test-browser-quick:
    nu test-browser.nu --skip-build
