#!/usr/bin/env bash
#
# intercept communication with true pinentry to cache pin in kernel session keyring

pinentry="${1:-pinentry}"

coproc pproc { $pinentry; }

function psend() {
  echo "$@" >&${pproc[1]}
}

function preceive() {
  read presponse <&${pproc[0]}
}

function prelayback() {
  preceive
  echo "$presponse"
}

prelayback

while read line; do
  case "$line" in
    BYE )
      psend BYE
      prelayback
      break
      ;;
    SETDESC* )
      psend "$line"
      prelayback
      desc="${line#SETDESC }"
      ;;
    GETPIN )
      key="$(keyctl search @s user "$desc" 2>/dev/null)"
      if [ $? = 0 ]; then
        echo -n 'D '
        keyctl pipe "$key"
      else
        psend "$line"
        prelayback
        key="$(echo "${presponse#D }" | keyctl padd user "$desc" @s)"
        if [ "$PINENTRY_SESSIONCACHE_TIMEOUT" ]; then
          keyctl timeout "$key" "$PINENTRY_SESSIONCACHE_TIMEOUT"
        fi
      fi
      echo OK
      ;;
    * )
      psend "$line"
      prelayback
      ;;
  esac
done

# vim: ts=2 sw=2
