build:
  mkdir -p build
  rm -f build/out.cwasm
  mojo build --emit llvm --target-features "none" -o build/out.ll src/main.mojo
  sed -i '/call void @llvm\.lifetime\.\(start\|end\)/d' build/out.ll
  llc --mtriple=wasm64-wasi -filetype=obj build/out.ll
  wasm-ld --no-entry --export-all --allow-undefined -mwasm64 --initial-memory=268435456 -o build/out.wasm build/out.o

precompile: build
  mojo run -I ../wasmtime-mojo/src scripts/precompile.mojo

test: precompile
  mojo test -I ../wasmtime-mojo/src test/

test-js: build
  deno run --allow-read test-js/run.ts

test-all: test test-js

serve: build
  @echo "Open http://localhost:4507/examples/counter/"
  @echo "Open http://localhost:4507/examples/todo/"
  @echo "Open http://localhost:4507/examples/bench/"
  deno run --allow-net --allow-read jsr:@std/http/file-server
