build host:
    nixos-rebuild build --flake .#{{ host }} --print-build-logs

switch host:
    sudo nixos-rebuild switch --flake .#{{ host }} --print-build-logs

rekey:
    cd secrets && agenix --rekey
