dev: build-gqty
    deno run -A npm:next dev
    next dev

build: build-gqty build-next

build-next:
    export NEXT_PUBLIC_GIT_COMMIT_SHA=$(git rev-parse HEAD)
    deno run -A npm:next build

build-gqty:
    deno run -A npm:@gqty/cli generate

start: build
    deno run -A npm:serve -n out

clean:
    rm -Rf .next node_modules

lint:
    deno lint
