#!/usr/bin/env bash
# gen_test_runner.sh — Generate a single-file Mojo test with one function per test module.
#
# Scans test/test_*.mojo for all `fn test_*` and `def test_*` functions,
# then generates test/test_all.mojo with one `def test_<stem>()` per file
# that calls ALL tests from that file sequentially.
#
# Result: 26 test functions instead of 674.  `mojo test` spawns 26
# processes (one WasmInstance each) instead of 674, cutting total time
# from ~2m40s to ~30s.
#
# Usage:
#   bash scripts/gen_test_runner.sh
#   mojo test -I ../wasmtime-mojo/src test/test_all.mojo
#
# Or via justfile:
#   just test-fast

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEST_DIR="$PROJECT_DIR/test"
OUTPUT="$TEST_DIR/test_all.mojo"

# ---------------------------------------------------------------------------
# Collect test functions grouped by file
# ---------------------------------------------------------------------------

declare -A FILE_FUNCS   # file_stem -> newline-separated function names
declare -a FILE_ORDER   # preserve discovery order

for test_file in "$TEST_DIR"/test_*.mojo; do
    [ -f "$test_file" ] || continue
    stem="$(basename "$test_file" .mojo)"

    # Skip ourselves and any scratch files
    case "$stem" in
        test_all|test_all_small|test_all_probe) continue ;;
    esac

    # Extract function names: lines starting with `fn test_` or `def test_`
    funcs="$(grep -Po '^(?:fn|def) \Ktest_\w+' "$test_file" || true)"
    if [ -z "$funcs" ]; then
        continue
    fi

    FILE_FUNCS["$stem"]="$funcs"
    FILE_ORDER+=("$stem")
done

# ---------------------------------------------------------------------------
# Count totals
# ---------------------------------------------------------------------------

total=0
for stem in "${FILE_ORDER[@]}"; do
    count=$(echo "${FILE_FUNCS[$stem]}" | wc -w)
    total=$((total + count))
done

# ---------------------------------------------------------------------------
# Generate the runner
# ---------------------------------------------------------------------------

cat > "$OUTPUT" << 'HEADER'
# Auto-generated by scripts/gen_test_runner.sh — DO NOT EDIT.
#
# Single-file test suite with ONE test function per source module.
# Each function calls all tests from that module sequentially, so
# `mojo test` spawns ~26 processes instead of ~674.
#
# Regenerate:  bash scripts/gen_test_runner.sh
# Run:         mojo test -I ../wasmtime-mojo/src test/test_all.mojo
# Or:          just test-fast

from testing import assert_equal, assert_true, assert_false
HEADER

# ── Module imports ────────────────────────────────────────────────────────────

echo "" >> "$OUTPUT"
for stem in "${FILE_ORDER[@]}"; do
    echo "import $stem" >> "$OUTPUT"
done

# ── One wrapper function per module ───────────────────────────────────────────

echo "" >> "$OUTPUT"
for stem in "${FILE_ORDER[@]}"; do
    funcs="${FILE_FUNCS[$stem]}"
    count=$(echo "$funcs" | wc -w)

    # Strip leading "test_" from stem for the wrapper name to keep it short
    # but still unique.  E.g. test_algorithms -> test_all_algorithms
    short="${stem#test_}"

    echo "" >> "$OUTPUT"
    echo "# ── $stem ($count tests) ──" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "def test_all_${short}():" >> "$OUTPUT"
    echo "    \"\"\"$stem — $count tests.\"\"\"" >> "$OUTPUT"

    for fn_name in $funcs; do
        echo "    ${stem}.${fn_name}()" >> "$OUTPUT"
    done

    echo "" >> "$OUTPUT"
done

echo "Generated $OUTPUT — ${#FILE_ORDER[@]} grouped tests wrapping $total individual tests."
