build:
  mkdir -p build
  mojo build --emit-llvm --target-features "none" --emit shared-lib src/main.mojo > build/out.ll
  llc --mtriple=wasm64-wasi -filetype=obj build/out.ll
  wasm-ld --no-entry --export-all --allow-undefined -mwasm64 -o build/out.wasm build/out.o

server:
  python server.py
